import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="py-8 px-40 flex items-center justify-between">
          <Image
            src="crobor-logo.svg"
            alt="logo crobor"
            width={230}
            height={64}
          />
          <nav className="flex gap-2">
            <Link href="/">Home</Link>
            <Link href="/sobre">Sobre</Link>
            <Link href="/equipe">Equipe</Link>
            <Link href="/metas">Metas</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
